export const PermissionCodes = {
  USERS_CREATE: 'users:create',
  USERS_READ: 'users:read',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  USERS_READ_PHONE: 'users:read_phone',

  ROLES_READ: 'roles:read',
  ROLES_UPDATE: 'roles:update',

  PERMISSIONS_READ: 'permissions:read',
  PERMISSIONS_CREATE: 'permissions:create',
  PERMISSIONS_UPDATE: 'permissions:update',
  PERMISSIONS_DELETE: 'permissions:delete',

  COMPLAINTS_READ: 'complaints:read',
  COMPLAINTS_CREATE: 'complaints:create',
  COMPLAINTS_UPDATE: 'complaints:update',
  COMPLAINTS_APPROVE: 'complaints:approve',
  COMPLAINTS_REJECT: 'complaints:reject',

  INCIDENTS_READ: 'incidents:read',
  INCIDENTS_CREATE: 'incidents:create',
  INCIDENTS_UPDATE: 'incidents:update',
  INCIDENTS_HANDLE: 'incidents:handle',
  INCIDENTS_CLOSE: 'incidents:close',
  INCIDENTS_COMMENT: 'incidents:comment',
  INCIDENTS_VIEW_ALL: 'incidents:view_all',
  INCIDENTS_VIEW_ASSIGNED: 'incidents:view_assigned',
  INCIDENTS_ACKNOWLEDGE: 'incidents:acknowledge',
  INCIDENTS_ASSESS: 'incidents:assess',
  INCIDENTS_ASSIGN: 'incidents:assign',
  INCIDENTS_REASSIGN: 'incidents:reassign',
  INCIDENTS_RESPOND: 'incidents:respond',
  INCIDENTS_ARRIVE: 'incidents:arrive',
  INCIDENTS_CONTAIN: 'incidents:contain',
  INCIDENTS_RESOLVE: 'incidents:resolve',
  INCIDENTS_REOPEN: 'incidents:reopen',
  INCIDENTS_CANCEL: 'incidents:cancel',
  INCIDENTS_FALSE_ALARM: 'incidents:false_alarm',
  INCIDENTS_ESCALATE: 'incidents:escalate',
  INCIDENTS_REQUEST_SUPPORT: 'incidents:request_support',
  INCIDENTS_NOTES: 'incidents:notes',
  INCIDENTS_NOTES_CONFIDENTIAL: 'incidents:notes_confidential',
  INCIDENTS_CONTACTS: 'incidents:contacts',
  INCIDENTS_TASKS: 'incidents:tasks',
  INCIDENTS_FOLLOW_UPS: 'incidents:follow_ups',
  INCIDENTS_ATTACHMENTS: 'incidents:attachments',
  INCIDENTS_CONVERT_REFERRAL: 'incidents:convert_referral',
  INCIDENTS_CONVERT_ALERT: 'incidents:convert_alert',
  INCIDENTS_CONVERT_VIOLATION: 'incidents:convert_violation',
  OPERATIONS_ROOM_VIEW: 'operations_room:view',
  OPERATIONS_ROOM_MANAGE: 'operations_room:manage',
  EMERGENCY_PROCEDURES_VIEW: 'emergency_procedures:view',
  EMERGENCY_PROCEDURES_MANAGE: 'emergency_procedures:manage',

  PATROLS_READ: 'patrols:read',
  PATROLS_CREATE: 'patrols:create',
  PATROLS_UPDATE: 'patrols:update',

  VIOLATIONS_READ: 'violations:read',
  VIOLATIONS_CREATE: 'violations:create',
  VIOLATIONS_UPDATE: 'violations:update',
  VIOLATIONS_ASSIGN: 'violations:assign',
  VIOLATIONS_CLOSE: 'violations:close',
  VIOLATIONS_STATS: 'violations:stats',

  VISITORS_READ: 'visitors:read',
  VISITORS_CREATE: 'visitors:create',
  VISITORS_UPDATE: 'visitors:update',
  VISITORS_ARRIVE: 'visitors:arrive',
  VISITORS_STATS: 'visitors:stats',
  HOSTS_READ: 'hosts:read',
  HOSTS_CREATE: 'hosts:create',
  HOSTS_UPDATE: 'hosts:update',
  HOSTS_DELETE: 'hosts:delete',
  MEETING_ROOMS_READ: 'meeting_rooms:read',
  MEETING_ROOMS_MANAGE: 'meeting_rooms:manage',
  FLOORS_READ: 'floors:read',
  FLOORS_UPDATE: 'floors:update',
  VISIT_EMAILS_READ: 'visit_emails:read',
  VISIT_EMAILS_INGEST: 'visit_emails:ingest',

  AUDIT_READ: 'audit:read',

  NOTIFICATIONS_READ: 'notifications:read',
  NOTIFICATIONS_UPDATE: 'notifications:update',
  NOTIFICATIONS_ACKNOWLEDGE: 'notifications:acknowledge',
  NOTIFICATIONS_PREFERENCES_READ: 'notifications:preferences_read',
  NOTIFICATIONS_PREFERENCES_UPDATE: 'notifications:preferences_update',
  NOTIFICATIONS_RULES_READ: 'notifications:rules_read',
  NOTIFICATIONS_RULES_MANAGE: 'notifications:rules_manage',
  NOTIFICATIONS_STATISTICS: 'notifications:statistics',

  COMMUNICATIONS_READ: 'communications:read',
  COMMUNICATIONS_CREATE: 'communications:create',
  COMMUNICATIONS_SEND: 'communications:send',
  COMMUNICATIONS_UPDATE: 'communications:update',
  COMMUNICATIONS_DELETE: 'communications:delete',
  COMMUNICATIONS_ATTACHMENTS: 'communications:attachments',
  COMMUNICATIONS_MANAGE: 'communications:manage',

  TASKS_READ: 'tasks:read',
  TASKS_CREATE: 'tasks:create',
  TASKS_UPDATE: 'tasks:update',
  TASKS_ASSIGN: 'tasks:assign',
  TASKS_ACCEPT: 'tasks:accept',
  TASKS_START: 'tasks:start',
  TASKS_WAIT: 'tasks:wait',
  TASKS_COMPLETE: 'tasks:complete',
  TASKS_REJECT: 'tasks:reject',
  TASKS_CANCEL: 'tasks:cancel',
  TASKS_ESCALATE: 'tasks:escalate',
  TASKS_EVIDENCE: 'tasks:evidence',
  TASKS_TIMELINE: 'tasks:timeline',

  DASHBOARD_READ: 'dashboard:read',
  DIRECTOR_DASHBOARD_READ: 'director:dashboard',

  REPORTS_READ: 'reports:read',

  REPORTS_DASHBOARD_VIEW: 'reports:dashboard_view',
  REPORTS_LIST: 'reports:list',
  REPORTS_VIEW: 'reports:view',
  REPORTS_GENERATE: 'reports:generate',
  REPORTS_GENERATE_DAILY: 'reports:generate_daily',
  REPORTS_GENERATE_SHIFT: 'reports:generate_shift',
  REPORTS_GENERATE_HANDOVER: 'reports:generate_handover',
  REPORTS_GENERATE_CUSTOM: 'reports:generate_custom',
  REPORTS_EXPORT_PDF: 'reports:export_pdf',
  REPORTS_EXPORT_CSV: 'reports:export_csv',
  REPORTS_SUBMIT: 'reports:submit',
  REPORTS_APPROVE: 'reports:approve',
  REPORTS_REJECT: 'reports:reject',
  REPORTS_RETURN: 'reports:return',
  REPORTS_ARCHIVE: 'reports:archive',
  REPORTS_CREATE_VERSION: 'reports:create_version',
  REPORTS_SCHEDULES_VIEW: 'reports:schedules_view',
  REPORTS_SCHEDULES_MANAGE: 'reports:schedules_manage',
  REPORTS_ACCESS_LOG_VIEW: 'reports:access_log_view',
  REPORTS_KPI_VIEW: 'reports:kpi_view',

  KPI_VIEW: 'kpi:view',
  KPI_INCIDENTS: 'kpi:incidents',
  KPI_RESPONSE_TIMES: 'kpi:response_times',
  KPI_PATROLS: 'kpi:patrols',
  KPI_CCTV_REFERRALS: 'kpi:cctv_referrals',
  KPI_PERMITS: 'kpi:permits',
  KPI_VIOLATIONS: 'kpi:violations',
  KPI_VISITORS: 'kpi:visitors',
  KPI_PERSONNEL: 'kpi:personnel',
  KPI_GROUPS: 'kpi:groups',
  KPI_SHIFTS: 'kpi:shifts',

  AUDIT_LOGS_VIEW: 'audit_logs:view',
  AUDIT_LOGS_VIEW_SENSITIVE: 'audit_logs:view_sensitive',
  AUDIT_LOGS_EXPORT: 'audit_logs:export',
  AUDIT_LOGS_STATISTICS: 'audit_logs:statistics',

  SETTINGS_READ: 'settings:read',
  SETTINGS_UPDATE: 'settings:update',

  CAMERA_REQUESTS_READ: 'camera_requests:read',
  CAMERA_REQUESTS_CREATE: 'camera_requests:create',
  CAMERA_REQUESTS_HANDLE: 'camera_requests:handle',
  VEHICLE_PERMITS_READ: 'vehicle_permits:read',
  CCTV_DASHBOARD_READ: 'cctv_dashboard:read',

  SHIFTS_READ: 'shifts:read',
  SHIFTS_UPDATE: 'shifts:update',
  SHIFTS_MANAGE: 'shifts:manage',
  SHIFTS_HANDOVER: 'shifts:handover',
  SHIFTS_STATS: 'shifts:stats',

  FIELD_MAP_VIEW: 'field_map:view',
  FIELD_MAP_MANAGE: 'field_map:manage',

  SECURITY_ZONES_VIEW: 'security_zones:view',
  SECURITY_ZONES_CREATE: 'security_zones:create',
  SECURITY_ZONES_UPDATE: 'security_zones:update',
  SECURITY_ZONES_DELETE: 'security_zones:delete',

  CHECKPOINTS_VIEW: 'checkpoints:view',
  CHECKPOINTS_CREATE: 'checkpoints:create',
  CHECKPOINTS_UPDATE: 'checkpoints:update',
  CHECKPOINTS_DELETE: 'checkpoints:delete',

  PATROL_ROUTES_VIEW: 'patrol_routes:view',
  PATROL_ROUTES_MANAGE: 'patrol_routes:manage',

  PATROL_SESSIONS_VIEW: 'patrol_sessions:view',
  PATROL_SESSIONS_CREATE: 'patrol_sessions:create',
  PATROL_SESSIONS_ASSIGN: 'patrol_sessions:assign',
  PATROL_SESSIONS_START: 'patrol_sessions:start',
  PATROL_SESSIONS_COMPLETE: 'patrol_sessions:complete',
  PATROL_SESSIONS_CANCEL: 'patrol_sessions:cancel',

  PERSONNEL_LOCATIONS_VIEW: 'personnel_locations:view',
  PERSONNEL_LOCATIONS_UPDATE_SELF: 'personnel_locations:update_self',
  PERSONNEL_LOCATIONS_UPDATE_ANY: 'personnel_locations:update_any',

  FIELD_ALERTS_VIEW: 'field_alerts:view',
  FIELD_ALERTS_CREATE: 'field_alerts:create',
  FIELD_ALERTS_ACKNOWLEDGE: 'field_alerts:acknowledge',
  FIELD_ALERTS_RESOLVE: 'field_alerts:resolve',

  CCTV_OPS_DASHBOARD_VIEW: 'cctv_operations:dashboard_view',

  PERMITS_VIEW: 'permits:view',
  PERMITS_CREATE: 'permits:create',
  PERMITS_UPDATE: 'permits:update',
  PERMITS_ACTIVATE: 'permits:activate',
  PERMITS_CANCEL: 'permits:cancel',
  PERMITS_REJECT: 'permits:reject',
  PERMITS_SHARE: 'permits:share',
  PERMITS_ACKNOWLEDGE: 'permits:acknowledge',
  PERMITS_VIEW_SENSITIVE: 'permits:view_sensitive_data',
  PERMITS_DOWNLOAD_ATTACHMENT: 'permits:download_attachment',

  SECURITY_REFERRALS_VIEW: 'security_referrals:view',
  SECURITY_REFERRALS_CREATE: 'security_referrals:create',
  SECURITY_REFERRALS_UPDATE: 'security_referrals:update',
  SECURITY_REFERRALS_SEND: 'security_referrals:send',
  SECURITY_REFERRALS_ASSIGN: 'security_referrals:assign',
  SECURITY_REFERRALS_RECEIVE: 'security_referrals:receive',
  SECURITY_REFERRALS_START: 'security_referrals:start',
  SECURITY_REFERRALS_ARRIVE: 'security_referrals:arrive',
  SECURITY_REFERRALS_RESOLVE: 'security_referrals:resolve',
  SECURITY_REFERRALS_REJECT: 'security_referrals:reject',
  SECURITY_REFERRALS_CANCEL: 'security_referrals:cancel',
  SECURITY_REFERRALS_ESCALATE: 'security_referrals:escalate',
  SECURITY_REFERRALS_CLOSE: 'security_referrals:close',
  SECURITY_REFERRALS_ADD_NOTE: 'security_referrals:add_note',
  SECURITY_REFERRALS_UPLOAD_ATTACHMENT: 'security_referrals:upload_attachment',
  SECURITY_REFERRALS_DOWNLOAD_ATTACHMENT: 'security_referrals:download_attachment',

  // Sprint 20 — mobile app
  MOBILE_APP_ACCESS: 'mobile:app_access',
  MOBILE_BOOTSTRAP: 'mobile:bootstrap',
  MOBILE_SYNC: 'mobile:sync',
  MOBILE_OFFLINE_OPERATIONS: 'mobile:offline_operations',
  MOBILE_DASHBOARD_GUARD: 'mobile:dashboard_guard',
  MOBILE_DASHBOARD_SUPERVISOR: 'mobile:dashboard_supervisor',
  MOBILE_DASHBOARD_CCTV: 'mobile:dashboard_cctv',
  MOBILE_DASHBOARD_OPERATIONS: 'mobile:dashboard_operations',
  MOBILE_INCIDENTS_VIEW: 'mobile:incidents_view',
  MOBILE_INCIDENTS_RESPOND: 'mobile:incidents_respond',
  MOBILE_INCIDENTS_CREATE: 'mobile:incidents_create',
  MOBILE_TASKS_VIEW: 'mobile:tasks_view',
  MOBILE_TASKS_UPDATE: 'mobile:tasks_update',
  MOBILE_PATROLS_VIEW: 'mobile:patrols_view',
  MOBILE_PATROLS_EXECUTE: 'mobile:patrols_execute',
  MOBILE_CHECKPOINTS_SCAN: 'mobile:checkpoints_scan',
  MOBILE_REFERRALS_VIEW: 'mobile:referrals_view',
  MOBILE_REFERRALS_CREATE: 'mobile:referrals_create',
  MOBILE_REFERRALS_RESPOND: 'mobile:referrals_respond',
  MOBILE_PERMITS_VIEW: 'mobile:permits_view',
  MOBILE_PERMITS_CREATE: 'mobile:permits_create',
  MOBILE_PERMITS_ACKNOWLEDGE: 'mobile:permits_acknowledge',
  MOBILE_VIOLATIONS_VIEW: 'mobile:violations_view',
  MOBILE_VIOLATIONS_CREATE: 'mobile:violations_create',
  MOBILE_HANDOVER_VIEW: 'mobile:handover_view',
  MOBILE_HANDOVER_SUBMIT: 'mobile:handover_submit',
  MOBILE_HANDOVER_RECEIVE: 'mobile:handover_receive',
  MOBILE_SOS_CREATE: 'mobile:sos_create',
  MOBILE_COMMUNICATIONS_VIEW: 'mobile:communications_view',
  MOBILE_COMMUNICATIONS_SEND: 'mobile:communications_send',
  MOBILE_SYNC_ISSUES_VIEW: 'mobile:sync_issues_view',
  MOBILE_DEVICES_MANAGE_SELF: 'mobile:devices_manage_self',
  MOBILE_DEVICES_MANAGE_ALL: 'mobile:devices_manage_all',
} as const;

export type PermissionCode = (typeof PermissionCodes)[keyof typeof PermissionCodes];

export interface PermissionDefinition {
  code: PermissionCode;
  resource: string;
  action: string;
  description: string;
}

export const PERMISSION_CATALOG: PermissionDefinition[] = [
  { code: PermissionCodes.USERS_CREATE, resource: 'users', action: 'create', description: 'Create users' },
  { code: PermissionCodes.USERS_READ, resource: 'users', action: 'read', description: 'List and view users' },
  { code: PermissionCodes.USERS_UPDATE, resource: 'users', action: 'update', description: 'Update users' },
  { code: PermissionCodes.USERS_DELETE, resource: 'users', action: 'delete', description: 'Soft-delete users' },
  {
    code: PermissionCodes.USERS_READ_PHONE,
    resource: 'users',
    action: 'read_phone',
    description: 'View employee phone numbers',
  },

  { code: PermissionCodes.ROLES_READ, resource: 'roles', action: 'read', description: 'List roles' },
  { code: PermissionCodes.ROLES_UPDATE, resource: 'roles', action: 'update', description: 'Update role permissions' },

  {
    code: PermissionCodes.PERMISSIONS_READ,
    resource: 'permissions',
    action: 'read',
    description: 'List permissions and policies',
  },
  {
    code: PermissionCodes.PERMISSIONS_CREATE,
    resource: 'permissions',
    action: 'create',
    description: 'Create permissions and policies',
  },
  {
    code: PermissionCodes.PERMISSIONS_UPDATE,
    resource: 'permissions',
    action: 'update',
    description: 'Update permissions and policies',
  },
  {
    code: PermissionCodes.PERMISSIONS_DELETE,
    resource: 'permissions',
    action: 'delete',
    description: 'Delete permissions and policies',
  },

  { code: PermissionCodes.COMPLAINTS_READ, resource: 'complaints', action: 'read', description: 'Read complaints' },
  {
    code: PermissionCodes.COMPLAINTS_CREATE,
    resource: 'complaints',
    action: 'create',
    description: 'Create complaints',
  },
  {
    code: PermissionCodes.COMPLAINTS_UPDATE,
    resource: 'complaints',
    action: 'update',
    description: 'Update complaints',
  },
  {
    code: PermissionCodes.COMPLAINTS_APPROVE,
    resource: 'complaints',
    action: 'approve',
    description: 'Approve complaints',
  },
  {
    code: PermissionCodes.COMPLAINTS_REJECT,
    resource: 'complaints',
    action: 'reject',
    description: 'Reject complaints',
  },

  { code: PermissionCodes.INCIDENTS_READ, resource: 'incidents', action: 'read', description: 'Read incidents' },
  {
    code: PermissionCodes.INCIDENTS_CREATE,
    resource: 'incidents',
    action: 'create',
    description: 'Create incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_UPDATE,
    resource: 'incidents',
    action: 'update',
    description: 'Update incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_HANDLE,
    resource: 'incidents',
    action: 'handle',
    description: 'Handle / assign incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_CLOSE,
    resource: 'incidents',
    action: 'close',
    description: 'Close incidents and generate PDF',
  },
  {
    code: PermissionCodes.INCIDENTS_COMMENT,
    resource: 'incidents',
    action: 'comment',
    description: 'Comment on incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_VIEW_ALL,
    resource: 'incidents',
    action: 'view_all',
    description: 'View all incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_VIEW_ASSIGNED,
    resource: 'incidents',
    action: 'view_assigned',
    description: 'View assigned incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_ACKNOWLEDGE,
    resource: 'incidents',
    action: 'acknowledge',
    description: 'Acknowledge incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_ASSESS,
    resource: 'incidents',
    action: 'assess',
    description: 'Assess incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_ASSIGN,
    resource: 'incidents',
    action: 'assign',
    description: 'Assign incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_REASSIGN,
    resource: 'incidents',
    action: 'reassign',
    description: 'Reassign incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_RESPOND,
    resource: 'incidents',
    action: 'respond',
    description: 'Start incident response',
  },
  {
    code: PermissionCodes.INCIDENTS_ARRIVE,
    resource: 'incidents',
    action: 'arrive',
    description: 'Mark on-scene arrival',
  },
  {
    code: PermissionCodes.INCIDENTS_CONTAIN,
    resource: 'incidents',
    action: 'contain',
    description: 'Mark incident contained',
  },
  {
    code: PermissionCodes.INCIDENTS_RESOLVE,
    resource: 'incidents',
    action: 'resolve',
    description: 'Resolve incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_REOPEN,
    resource: 'incidents',
    action: 'reopen',
    description: 'Reopen closed incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_CANCEL,
    resource: 'incidents',
    action: 'cancel',
    description: 'Cancel incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_FALSE_ALARM,
    resource: 'incidents',
    action: 'false_alarm',
    description: 'Mark incident as false alarm',
  },
  {
    code: PermissionCodes.INCIDENTS_ESCALATE,
    resource: 'incidents',
    action: 'escalate',
    description: 'Escalate incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_REQUEST_SUPPORT,
    resource: 'incidents',
    action: 'request_support',
    description: 'Request support on incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_NOTES,
    resource: 'incidents',
    action: 'notes',
    description: 'Add and view incident notes',
  },
  {
    code: PermissionCodes.INCIDENTS_NOTES_CONFIDENTIAL,
    resource: 'incidents',
    action: 'notes_confidential',
    description: 'Add and view confidential incident notes',
  },
  {
    code: PermissionCodes.INCIDENTS_CONTACTS,
    resource: 'incidents',
    action: 'contacts',
    description: 'Log external contacts for incidents',
  },
  {
    code: PermissionCodes.INCIDENTS_TASKS,
    resource: 'incidents',
    action: 'tasks',
    description: 'Manage incident tasks',
  },
  {
    code: PermissionCodes.INCIDENTS_FOLLOW_UPS,
    resource: 'incidents',
    action: 'follow_ups',
    description: 'Manage incident follow-ups',
  },
  {
    code: PermissionCodes.INCIDENTS_ATTACHMENTS,
    resource: 'incidents',
    action: 'attachments',
    description: 'Upload and download incident attachments',
  },
  {
    code: PermissionCodes.INCIDENTS_CONVERT_REFERRAL,
    resource: 'incidents',
    action: 'convert_referral',
    description: 'Convert security referral to incident',
  },
  {
    code: PermissionCodes.INCIDENTS_CONVERT_ALERT,
    resource: 'incidents',
    action: 'convert_alert',
    description: 'Convert field alert to incident',
  },
  {
    code: PermissionCodes.INCIDENTS_CONVERT_VIOLATION,
    resource: 'incidents',
    action: 'convert_violation',
    description: 'Convert vehicle violation to incident',
  },
  {
    code: PermissionCodes.OPERATIONS_ROOM_VIEW,
    resource: 'operations_room',
    action: 'view',
    description: 'View operations room dashboard',
  },
  {
    code: PermissionCodes.OPERATIONS_ROOM_MANAGE,
    resource: 'operations_room',
    action: 'manage',
    description: 'Manage operations room',
  },
  {
    code: PermissionCodes.EMERGENCY_PROCEDURES_VIEW,
    resource: 'emergency_procedures',
    action: 'view',
    description: 'View emergency procedures',
  },
  {
    code: PermissionCodes.EMERGENCY_PROCEDURES_MANAGE,
    resource: 'emergency_procedures',
    action: 'manage',
    description: 'Manage emergency procedures',
  },

  { code: PermissionCodes.PATROLS_READ, resource: 'patrols', action: 'read', description: 'Read patrols' },
  { code: PermissionCodes.PATROLS_CREATE, resource: 'patrols', action: 'create', description: 'Create patrols' },
  { code: PermissionCodes.PATROLS_UPDATE, resource: 'patrols', action: 'update', description: 'Update patrols' },

  {
    code: PermissionCodes.VIOLATIONS_READ,
    resource: 'violations',
    action: 'read',
    description: 'Read vehicle violations',
  },
  {
    code: PermissionCodes.VIOLATIONS_CREATE,
    resource: 'violations',
    action: 'create',
    description: 'Create vehicle violations',
  },
  {
    code: PermissionCodes.VIOLATIONS_UPDATE,
    resource: 'violations',
    action: 'update',
    description: 'Update vehicle violations',
  },
  {
    code: PermissionCodes.VIOLATIONS_ASSIGN,
    resource: 'violations',
    action: 'assign',
    description: 'Assign vehicle violations',
  },
  {
    code: PermissionCodes.VIOLATIONS_CLOSE,
    resource: 'violations',
    action: 'close',
    description: 'Close / resolve vehicle violations',
  },
  {
    code: PermissionCodes.VIOLATIONS_STATS,
    resource: 'violations',
    action: 'stats',
    description: 'View violation statistics',
  },

  { code: PermissionCodes.VISITORS_READ, resource: 'visitors', action: 'read', description: 'Read visitors' },
  { code: PermissionCodes.VISITORS_CREATE, resource: 'visitors', action: 'create', description: 'Create visitors' },
  { code: PermissionCodes.VISITORS_UPDATE, resource: 'visitors', action: 'update', description: 'Update visitors' },
  {
    code: PermissionCodes.VISITORS_ARRIVE,
    resource: 'visitors',
    action: 'arrive',
    description: 'Mark visitor arrived and notify host',
  },
  { code: PermissionCodes.VISITORS_STATS, resource: 'visitors', action: 'stats', description: 'Visitor statistics' },
  { code: PermissionCodes.HOSTS_READ, resource: 'hosts', action: 'read', description: 'Read hosts' },
  { code: PermissionCodes.HOSTS_CREATE, resource: 'hosts', action: 'create', description: 'Create hosts' },
  { code: PermissionCodes.HOSTS_UPDATE, resource: 'hosts', action: 'update', description: 'Update hosts' },
  { code: PermissionCodes.HOSTS_DELETE, resource: 'hosts', action: 'delete', description: 'Delete hosts' },
  {
    code: PermissionCodes.MEETING_ROOMS_READ,
    resource: 'meeting_rooms',
    action: 'read',
    description: 'Read meeting rooms',
  },
  {
    code: PermissionCodes.MEETING_ROOMS_MANAGE,
    resource: 'meeting_rooms',
    action: 'manage',
    description: 'Create/update/delete meeting rooms',
  },
  { code: PermissionCodes.FLOORS_READ, resource: 'floors', action: 'read', description: 'Read floors' },
  { code: PermissionCodes.FLOORS_UPDATE, resource: 'floors', action: 'update', description: 'Update floors' },
  {
    code: PermissionCodes.VISIT_EMAILS_READ,
    resource: 'visit_emails',
    action: 'read',
    description: 'Read visit email ingest queue',
  },
  {
    code: PermissionCodes.VISIT_EMAILS_INGEST,
    resource: 'visit_emails',
    action: 'ingest',
    description: 'Ingest visit emails for mail parser',
  },

  { code: PermissionCodes.AUDIT_READ, resource: 'audit', action: 'read', description: 'Read audit logs' },

  {
    code: PermissionCodes.NOTIFICATIONS_READ,
    resource: 'notifications',
    action: 'read',
    description: 'Read user notifications inbox',
  },
  {
    code: PermissionCodes.NOTIFICATIONS_UPDATE,
    resource: 'notifications',
    action: 'update',
    description: 'Mark notifications as read',
  },
  {
    code: PermissionCodes.NOTIFICATIONS_ACKNOWLEDGE,
    resource: 'notifications',
    action: 'acknowledge',
    description: 'Acknowledge notifications requiring acknowledgement',
  },
  {
    code: PermissionCodes.NOTIFICATIONS_PREFERENCES_READ,
    resource: 'notifications',
    action: 'preferences_read',
    description: 'Read notification preferences',
  },
  {
    code: PermissionCodes.NOTIFICATIONS_PREFERENCES_UPDATE,
    resource: 'notifications',
    action: 'preferences_update',
    description: 'Update notification preferences',
  },
  {
    code: PermissionCodes.NOTIFICATIONS_RULES_READ,
    resource: 'notifications',
    action: 'rules_read',
    description: 'Read notification rules',
  },
  {
    code: PermissionCodes.NOTIFICATIONS_RULES_MANAGE,
    resource: 'notifications',
    action: 'rules_manage',
    description: 'Manage notification rules',
  },
  {
    code: PermissionCodes.NOTIFICATIONS_STATISTICS,
    resource: 'notifications',
    action: 'statistics',
    description: 'View notification statistics',
  },
  {
    code: PermissionCodes.COMMUNICATIONS_READ,
    resource: 'communications',
    action: 'read',
    description: 'Read internal conversations and messages',
  },
  {
    code: PermissionCodes.COMMUNICATIONS_CREATE,
    resource: 'communications',
    action: 'create',
    description: 'Create internal conversations',
  },
  {
    code: PermissionCodes.COMMUNICATIONS_SEND,
    resource: 'communications',
    action: 'send',
    description: 'Send internal messages',
  },
  {
    code: PermissionCodes.COMMUNICATIONS_UPDATE,
    resource: 'communications',
    action: 'update',
    description: 'Update conversations',
  },
  {
    code: PermissionCodes.COMMUNICATIONS_DELETE,
    resource: 'communications',
    action: 'delete',
    description: 'Soft-delete messages',
  },
  {
    code: PermissionCodes.COMMUNICATIONS_ATTACHMENTS,
    resource: 'communications',
    action: 'attachments',
    description: 'Upload and download message attachments',
  },
  {
    code: PermissionCodes.COMMUNICATIONS_MANAGE,
    resource: 'communications',
    action: 'manage',
    description: 'Manage all communications',
  },

  { code: PermissionCodes.TASKS_READ, resource: 'tasks', action: 'read', description: 'Read tasks' },
  { code: PermissionCodes.TASKS_CREATE, resource: 'tasks', action: 'create', description: 'Create tasks' },
  { code: PermissionCodes.TASKS_UPDATE, resource: 'tasks', action: 'update', description: 'Update and complete tasks' },
  { code: PermissionCodes.TASKS_ASSIGN, resource: 'tasks', action: 'assign', description: 'Assign tasks to users' },
  { code: PermissionCodes.TASKS_ACCEPT, resource: 'tasks', action: 'accept', description: 'Accept assigned tasks' },
  { code: PermissionCodes.TASKS_START, resource: 'tasks', action: 'start', description: 'Start accepted tasks' },
  { code: PermissionCodes.TASKS_WAIT, resource: 'tasks', action: 'wait', description: 'Mark tasks as waiting' },
  { code: PermissionCodes.TASKS_COMPLETE, resource: 'tasks', action: 'complete', description: 'Complete tasks' },
  { code: PermissionCodes.TASKS_REJECT, resource: 'tasks', action: 'reject', description: 'Reject assigned tasks' },
  { code: PermissionCodes.TASKS_CANCEL, resource: 'tasks', action: 'cancel', description: 'Cancel tasks' },
  { code: PermissionCodes.TASKS_ESCALATE, resource: 'tasks', action: 'escalate', description: 'Escalate tasks' },
  { code: PermissionCodes.TASKS_EVIDENCE, resource: 'tasks', action: 'evidence', description: 'Upload task evidence' },
  { code: PermissionCodes.TASKS_TIMELINE, resource: 'tasks', action: 'timeline', description: 'View task timeline' },

  {
    code: PermissionCodes.DASHBOARD_READ,
    resource: 'dashboard',
    action: 'read',
    description: 'View dashboard summary',
  },
  {
    code: PermissionCodes.DIRECTOR_DASHBOARD_READ,
    resource: 'director',
    action: 'dashboard',
    description: 'View security director dashboard',
  },
  {
    code: PermissionCodes.REPORTS_READ,
    resource: 'reports',
    action: 'read',
    description: 'View and export operational reports',
  },
  {
    code: PermissionCodes.REPORTS_DASHBOARD_VIEW,
    resource: 'reports',
    action: 'dashboard_view',
    description: 'View reports dashboard overview',
  },
  { code: PermissionCodes.REPORTS_LIST, resource: 'reports', action: 'list', description: 'List saved reports' },
  { code: PermissionCodes.REPORTS_VIEW, resource: 'reports', action: 'view', description: 'View saved report details' },
  {
    code: PermissionCodes.REPORTS_GENERATE,
    resource: 'reports',
    action: 'generate',
    description: 'Generate security reports',
  },
  {
    code: PermissionCodes.REPORTS_GENERATE_DAILY,
    resource: 'reports',
    action: 'generate_daily',
    description: 'Generate daily security reports',
  },
  {
    code: PermissionCodes.REPORTS_GENERATE_SHIFT,
    resource: 'reports',
    action: 'generate_shift',
    description: 'Generate shift reports',
  },
  {
    code: PermissionCodes.REPORTS_GENERATE_HANDOVER,
    resource: 'reports',
    action: 'generate_handover',
    description: 'Generate handover reports',
  },
  {
    code: PermissionCodes.REPORTS_GENERATE_CUSTOM,
    resource: 'reports',
    action: 'generate_custom',
    description: 'Generate custom allowlisted reports',
  },
  {
    code: PermissionCodes.REPORTS_EXPORT_PDF,
    resource: 'reports',
    action: 'export_pdf',
    description: 'Export reports as PDF',
  },
  {
    code: PermissionCodes.REPORTS_EXPORT_CSV,
    resource: 'reports',
    action: 'export_csv',
    description: 'Export reports as CSV',
  },
  {
    code: PermissionCodes.REPORTS_SUBMIT,
    resource: 'reports',
    action: 'submit',
    description: 'Submit reports for approval',
  },
  {
    code: PermissionCodes.REPORTS_APPROVE,
    resource: 'reports',
    action: 'approve',
    description: 'Approve reports',
  },
  {
    code: PermissionCodes.REPORTS_REJECT,
    resource: 'reports',
    action: 'reject',
    description: 'Reject reports',
  },
  {
    code: PermissionCodes.REPORTS_RETURN,
    resource: 'reports',
    action: 'return',
    description: 'Return reports for edit',
  },
  {
    code: PermissionCodes.REPORTS_ARCHIVE,
    resource: 'reports',
    action: 'archive',
    description: 'Archive approved reports',
  },
  {
    code: PermissionCodes.REPORTS_CREATE_VERSION,
    resource: 'reports',
    action: 'create_version',
    description: 'Create new report version',
  },
  {
    code: PermissionCodes.REPORTS_SCHEDULES_VIEW,
    resource: 'reports',
    action: 'schedules_view',
    description: 'View report schedules',
  },
  {
    code: PermissionCodes.REPORTS_SCHEDULES_MANAGE,
    resource: 'reports',
    action: 'schedules_manage',
    description: 'Manage report schedules',
  },
  {
    code: PermissionCodes.REPORTS_ACCESS_LOG_VIEW,
    resource: 'reports',
    action: 'access_log_view',
    description: 'View report access logs',
  },
  {
    code: PermissionCodes.REPORTS_KPI_VIEW,
    resource: 'reports',
    action: 'kpi_view',
    description: 'View report KPIs',
  },
  { code: PermissionCodes.KPI_VIEW, resource: 'kpi', action: 'view', description: 'View KPI dashboard' },
  { code: PermissionCodes.KPI_INCIDENTS, resource: 'kpi', action: 'incidents', description: 'View incident KPIs' },
  {
    code: PermissionCodes.KPI_RESPONSE_TIMES,
    resource: 'kpi',
    action: 'response_times',
    description: 'View response time KPIs',
  },
  { code: PermissionCodes.KPI_PATROLS, resource: 'kpi', action: 'patrols', description: 'View patrol KPIs' },
  {
    code: PermissionCodes.KPI_CCTV_REFERRALS,
    resource: 'kpi',
    action: 'cctv_referrals',
    description: 'View CCTV referral KPIs',
  },
  { code: PermissionCodes.KPI_PERMITS, resource: 'kpi', action: 'permits', description: 'View permit KPIs' },
  {
    code: PermissionCodes.KPI_VIOLATIONS,
    resource: 'kpi',
    action: 'violations',
    description: 'View violation KPIs',
  },
  { code: PermissionCodes.KPI_VISITORS, resource: 'kpi', action: 'visitors', description: 'View visitor KPIs' },
  {
    code: PermissionCodes.KPI_PERSONNEL,
    resource: 'kpi',
    action: 'personnel',
    description: 'View personnel KPIs',
  },
  { code: PermissionCodes.KPI_GROUPS, resource: 'kpi', action: 'groups', description: 'View group KPIs' },
  { code: PermissionCodes.KPI_SHIFTS, resource: 'kpi', action: 'shifts', description: 'View shift KPIs' },
  {
    code: PermissionCodes.AUDIT_LOGS_VIEW,
    resource: 'audit_logs',
    action: 'view',
    description: 'View audit logs',
  },
  {
    code: PermissionCodes.AUDIT_LOGS_VIEW_SENSITIVE,
    resource: 'audit_logs',
    action: 'view_sensitive',
    description: 'View sensitive audit log details',
  },
  {
    code: PermissionCodes.AUDIT_LOGS_EXPORT,
    resource: 'audit_logs',
    action: 'export',
    description: 'Export audit logs',
  },
  {
    code: PermissionCodes.AUDIT_LOGS_STATISTICS,
    resource: 'audit_logs',
    action: 'statistics',
    description: 'View audit log statistics',
  },
  {
    code: PermissionCodes.SETTINGS_READ,
    resource: 'settings',
    action: 'read',
    description: 'Read system settings and org lookups',
  },
  {
    code: PermissionCodes.SETTINGS_UPDATE,
    resource: 'settings',
    action: 'update',
    description: 'Update system settings and org lookups',
  },

  {
    code: PermissionCodes.CAMERA_REQUESTS_READ,
    resource: 'camera_requests',
    action: 'read',
    description: 'Read CCTV camera lookup requests',
  },
  {
    code: PermissionCodes.CAMERA_REQUESTS_CREATE,
    resource: 'camera_requests',
    action: 'create',
    description: 'Create CCTV camera lookup requests',
  },
  {
    code: PermissionCodes.CAMERA_REQUESTS_HANDLE,
    resource: 'camera_requests',
    action: 'handle',
    description: 'Handle CCTV camera lookup requests',
  },
  {
    code: PermissionCodes.VEHICLE_PERMITS_READ,
    resource: 'vehicle_permits',
    action: 'read',
    description: 'Search vehicle parking permits',
  },
  {
    code: PermissionCodes.CCTV_DASHBOARD_READ,
    resource: 'cctv_dashboard',
    action: 'read',
    description: 'View CCTV control room dashboard',
  },

  { code: PermissionCodes.SHIFTS_READ, resource: 'shifts', action: 'read', description: 'Read shift roster and ops board' },
  {
    code: PermissionCodes.SHIFTS_UPDATE,
    resource: 'shifts',
    action: 'update',
    description: 'Update personnel operational status',
  },
  {
    code: PermissionCodes.SHIFTS_MANAGE,
    resource: 'shifts',
    action: 'manage',
    description: 'Manage shift cycle configuration',
  },
  {
    code: PermissionCodes.SHIFTS_HANDOVER,
    resource: 'shifts',
    action: 'handover',
    description: 'Manage shift handover workflow',
  },
  {
    code: PermissionCodes.SHIFTS_STATS,
    resource: 'shifts',
    action: 'stats',
    description: 'View shift statistics',
  },

  { code: PermissionCodes.FIELD_MAP_VIEW, resource: 'field_map', action: 'view', description: 'View field operations map' },
  { code: PermissionCodes.FIELD_MAP_MANAGE, resource: 'field_map', action: 'manage', description: 'Manage field operations map' },

  { code: PermissionCodes.SECURITY_ZONES_VIEW, resource: 'security_zones', action: 'view', description: 'View security zones' },
  { code: PermissionCodes.SECURITY_ZONES_CREATE, resource: 'security_zones', action: 'create', description: 'Create security zones' },
  { code: PermissionCodes.SECURITY_ZONES_UPDATE, resource: 'security_zones', action: 'update', description: 'Update security zones' },
  { code: PermissionCodes.SECURITY_ZONES_DELETE, resource: 'security_zones', action: 'delete', description: 'Delete or disable security zones' },

  { code: PermissionCodes.CHECKPOINTS_VIEW, resource: 'checkpoints', action: 'view', description: 'View security checkpoints' },
  { code: PermissionCodes.CHECKPOINTS_CREATE, resource: 'checkpoints', action: 'create', description: 'Create security checkpoints' },
  { code: PermissionCodes.CHECKPOINTS_UPDATE, resource: 'checkpoints', action: 'update', description: 'Update security checkpoints' },
  { code: PermissionCodes.CHECKPOINTS_DELETE, resource: 'checkpoints', action: 'delete', description: 'Delete or disable checkpoints' },

  { code: PermissionCodes.PATROL_ROUTES_VIEW, resource: 'patrol_routes', action: 'view', description: 'View patrol routes' },
  { code: PermissionCodes.PATROL_ROUTES_MANAGE, resource: 'patrol_routes', action: 'manage', description: 'Create and manage patrol routes' },

  { code: PermissionCodes.PATROL_SESSIONS_VIEW, resource: 'patrol_sessions', action: 'view', description: 'View patrol sessions' },
  { code: PermissionCodes.PATROL_SESSIONS_CREATE, resource: 'patrol_sessions', action: 'create', description: 'Create patrol sessions' },
  { code: PermissionCodes.PATROL_SESSIONS_ASSIGN, resource: 'patrol_sessions', action: 'assign', description: 'Assign patrol sessions' },
  { code: PermissionCodes.PATROL_SESSIONS_START, resource: 'patrol_sessions', action: 'start', description: 'Start patrol sessions' },
  { code: PermissionCodes.PATROL_SESSIONS_COMPLETE, resource: 'patrol_sessions', action: 'complete', description: 'Complete patrol sessions and visit checkpoints' },
  { code: PermissionCodes.PATROL_SESSIONS_CANCEL, resource: 'patrol_sessions', action: 'cancel', description: 'Cancel patrol sessions' },

  { code: PermissionCodes.PERSONNEL_LOCATIONS_VIEW, resource: 'personnel_locations', action: 'view', description: 'View personnel locations' },
  {
    code: PermissionCodes.PERSONNEL_LOCATIONS_UPDATE_SELF,
    resource: 'personnel_locations',
    action: 'update_self',
    description: 'Update own personnel location',
  },
  {
    code: PermissionCodes.PERSONNEL_LOCATIONS_UPDATE_ANY,
    resource: 'personnel_locations',
    action: 'update_any',
    description: 'Manually update any personnel location',
  },

  { code: PermissionCodes.FIELD_ALERTS_VIEW, resource: 'field_alerts', action: 'view', description: 'View field alerts' },
  { code: PermissionCodes.FIELD_ALERTS_CREATE, resource: 'field_alerts', action: 'create', description: 'Create field alerts and SOS' },
  { code: PermissionCodes.FIELD_ALERTS_ACKNOWLEDGE, resource: 'field_alerts', action: 'acknowledge', description: 'Acknowledge field alerts' },
  { code: PermissionCodes.FIELD_ALERTS_RESOLVE, resource: 'field_alerts', action: 'resolve', description: 'Resolve or cancel field alerts' },

  {
    code: PermissionCodes.CCTV_OPS_DASHBOARD_VIEW,
    resource: 'cctv_operations',
    action: 'dashboard_view',
    description: 'View CCTV operations center dashboard',
  },
  { code: PermissionCodes.PERMITS_VIEW, resource: 'permits', action: 'view', description: 'View security permits' },
  { code: PermissionCodes.PERMITS_CREATE, resource: 'permits', action: 'create', description: 'Create security permits' },
  { code: PermissionCodes.PERMITS_UPDATE, resource: 'permits', action: 'update', description: 'Update security permits' },
  { code: PermissionCodes.PERMITS_ACTIVATE, resource: 'permits', action: 'activate', description: 'Activate security permits' },
  { code: PermissionCodes.PERMITS_CANCEL, resource: 'permits', action: 'cancel', description: 'Cancel security permits' },
  { code: PermissionCodes.PERMITS_REJECT, resource: 'permits', action: 'reject', description: 'Reject security permits' },
  { code: PermissionCodes.PERMITS_SHARE, resource: 'permits', action: 'share', description: 'Share security permits' },
  { code: PermissionCodes.PERMITS_ACKNOWLEDGE, resource: 'permits', action: 'acknowledge', description: 'Acknowledge shared permits' },
  {
    code: PermissionCodes.PERMITS_VIEW_SENSITIVE,
    resource: 'permits',
    action: 'view_sensitive_data',
    description: 'View full national ID on permits',
  },
  {
    code: PermissionCodes.PERMITS_DOWNLOAD_ATTACHMENT,
    resource: 'permits',
    action: 'download_attachment',
    description: 'Download permit attachments',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_VIEW,
    resource: 'security_referrals',
    action: 'view',
    description: 'View security referrals',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_CREATE,
    resource: 'security_referrals',
    action: 'create',
    description: 'Create security referrals',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_UPDATE,
    resource: 'security_referrals',
    action: 'update',
    description: 'Update security referrals',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_SEND,
    resource: 'security_referrals',
    action: 'send',
    description: 'Send security referrals',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_ASSIGN,
    resource: 'security_referrals',
    action: 'assign',
    description: 'Assign or reassign security referrals',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_RECEIVE,
    resource: 'security_referrals',
    action: 'receive',
    description: 'Receive assigned security referrals',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_START,
    resource: 'security_referrals',
    action: 'start',
    description: 'Start verification on security referrals',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_ARRIVE,
    resource: 'security_referrals',
    action: 'arrive',
    description: 'Mark arrival at referral location',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_RESOLVE,
    resource: 'security_referrals',
    action: 'resolve',
    description: 'Resolve security referrals in the field',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_REJECT,
    resource: 'security_referrals',
    action: 'reject',
    description: 'Reject security referrals',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_CANCEL,
    resource: 'security_referrals',
    action: 'cancel',
    description: 'Cancel security referrals before receive',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_ESCALATE,
    resource: 'security_referrals',
    action: 'escalate',
    description: 'Escalate security referrals',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_CLOSE,
    resource: 'security_referrals',
    action: 'close',
    description: 'Close security referrals (supervisor+)',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_ADD_NOTE,
    resource: 'security_referrals',
    action: 'add_note',
    description: 'Add notes to security referrals',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_UPLOAD_ATTACHMENT,
    resource: 'security_referrals',
    action: 'upload_attachment',
    description: 'Upload referral attachments',
  },
  {
    code: PermissionCodes.SECURITY_REFERRALS_DOWNLOAD_ATTACHMENT,
    resource: 'security_referrals',
    action: 'download_attachment',
    description: 'Download referral attachments',
  },

  // Sprint 20 — mobile
  { code: PermissionCodes.MOBILE_APP_ACCESS, resource: 'mobile', action: 'app_access', description: 'Access mobile application' },
  { code: PermissionCodes.MOBILE_BOOTSTRAP, resource: 'mobile', action: 'bootstrap', description: 'Load mobile bootstrap payload' },
  { code: PermissionCodes.MOBILE_SYNC, resource: 'mobile', action: 'sync', description: 'Pull and push mobile sync' },
  { code: PermissionCodes.MOBILE_OFFLINE_OPERATIONS, resource: 'mobile', action: 'offline_operations', description: 'Submit offline sync batch operations' },
  { code: PermissionCodes.MOBILE_DASHBOARD_GUARD, resource: 'mobile', action: 'dashboard_guard', description: 'Mobile guard dashboard' },
  { code: PermissionCodes.MOBILE_DASHBOARD_SUPERVISOR, resource: 'mobile', action: 'dashboard_supervisor', description: 'Mobile supervisor dashboard' },
  { code: PermissionCodes.MOBILE_DASHBOARD_CCTV, resource: 'mobile', action: 'dashboard_cctv', description: 'Mobile CCTV dashboard' },
  { code: PermissionCodes.MOBILE_DASHBOARD_OPERATIONS, resource: 'mobile', action: 'dashboard_operations', description: 'Mobile operations dashboard' },
  { code: PermissionCodes.MOBILE_INCIDENTS_VIEW, resource: 'mobile', action: 'incidents_view', description: 'View incidents on mobile' },
  { code: PermissionCodes.MOBILE_INCIDENTS_RESPOND, resource: 'mobile', action: 'incidents_respond', description: 'Respond to incidents on mobile' },
  { code: PermissionCodes.MOBILE_INCIDENTS_CREATE, resource: 'mobile', action: 'incidents_create', description: 'Create incidents on mobile' },
  { code: PermissionCodes.MOBILE_TASKS_VIEW, resource: 'mobile', action: 'tasks_view', description: 'View tasks on mobile' },
  { code: PermissionCodes.MOBILE_TASKS_UPDATE, resource: 'mobile', action: 'tasks_update', description: 'Update tasks on mobile' },
  { code: PermissionCodes.MOBILE_PATROLS_VIEW, resource: 'mobile', action: 'patrols_view', description: 'View patrols on mobile' },
  { code: PermissionCodes.MOBILE_PATROLS_EXECUTE, resource: 'mobile', action: 'patrols_execute', description: 'Execute patrols on mobile' },
  { code: PermissionCodes.MOBILE_CHECKPOINTS_SCAN, resource: 'mobile', action: 'checkpoints_scan', description: 'Scan checkpoints on mobile' },
  { code: PermissionCodes.MOBILE_REFERRALS_VIEW, resource: 'mobile', action: 'referrals_view', description: 'View referrals on mobile' },
  { code: PermissionCodes.MOBILE_REFERRALS_CREATE, resource: 'mobile', action: 'referrals_create', description: 'Create referrals on mobile' },
  { code: PermissionCodes.MOBILE_REFERRALS_RESPOND, resource: 'mobile', action: 'referrals_respond', description: 'Respond to referrals on mobile' },
  { code: PermissionCodes.MOBILE_PERMITS_VIEW, resource: 'mobile', action: 'permits_view', description: 'View permits on mobile' },
  { code: PermissionCodes.MOBILE_PERMITS_CREATE, resource: 'mobile', action: 'permits_create', description: 'Create permits on mobile' },
  { code: PermissionCodes.MOBILE_PERMITS_ACKNOWLEDGE, resource: 'mobile', action: 'permits_acknowledge', description: 'Acknowledge permits on mobile' },
  { code: PermissionCodes.MOBILE_VIOLATIONS_VIEW, resource: 'mobile', action: 'violations_view', description: 'View violations on mobile' },
  { code: PermissionCodes.MOBILE_VIOLATIONS_CREATE, resource: 'mobile', action: 'violations_create', description: 'Create violations on mobile' },
  { code: PermissionCodes.MOBILE_HANDOVER_VIEW, resource: 'mobile', action: 'handover_view', description: 'View وردية handovers on mobile' },
  { code: PermissionCodes.MOBILE_HANDOVER_SUBMIT, resource: 'mobile', action: 'handover_submit', description: 'Submit وردية handover on mobile' },
  { code: PermissionCodes.MOBILE_HANDOVER_RECEIVE, resource: 'mobile', action: 'handover_receive', description: 'Receive وردية handover on mobile' },
  { code: PermissionCodes.MOBILE_SOS_CREATE, resource: 'mobile', action: 'sos_create', description: 'Create SOS from mobile' },
  { code: PermissionCodes.MOBILE_COMMUNICATIONS_VIEW, resource: 'mobile', action: 'communications_view', description: 'View communications on mobile' },
  { code: PermissionCodes.MOBILE_COMMUNICATIONS_SEND, resource: 'mobile', action: 'communications_send', description: 'Send communications on mobile' },
  { code: PermissionCodes.MOBILE_SYNC_ISSUES_VIEW, resource: 'mobile', action: 'sync_issues_view', description: 'View mobile sync issues' },
  { code: PermissionCodes.MOBILE_DEVICES_MANAGE_SELF, resource: 'mobile', action: 'devices_manage_self', description: 'Manage own mobile devices' },
  { code: PermissionCodes.MOBILE_DEVICES_MANAGE_ALL, resource: 'mobile', action: 'devices_manage_all', description: 'Manage all mobile devices' },
];

/** Sprint 10 inbox / dashboard permissions granted to every role. */
const SPRINT10_BASE: PermissionCode[] = [
  PermissionCodes.NOTIFICATIONS_READ,
  PermissionCodes.NOTIFICATIONS_UPDATE,
  PermissionCodes.TASKS_READ,
  PermissionCodes.DASHBOARD_READ,
];

const SPRINT10_TASK_MANAGE: PermissionCode[] = [
  PermissionCodes.TASKS_CREATE,
  PermissionCodes.TASKS_UPDATE,
  PermissionCodes.TASKS_ASSIGN,
];

/** Sprint 19 — notifications / communications / task lifecycle. */
const SPRINT19_NOTIFICATIONS_BASE: PermissionCode[] = [
  PermissionCodes.NOTIFICATIONS_ACKNOWLEDGE,
  PermissionCodes.NOTIFICATIONS_PREFERENCES_READ,
  PermissionCodes.NOTIFICATIONS_PREFERENCES_UPDATE,
  PermissionCodes.NOTIFICATIONS_STATISTICS,
];

const SPRINT19_COMMS_BASE: PermissionCode[] = [
  PermissionCodes.COMMUNICATIONS_READ,
  PermissionCodes.COMMUNICATIONS_CREATE,
  PermissionCodes.COMMUNICATIONS_SEND,
  PermissionCodes.COMMUNICATIONS_UPDATE,
  PermissionCodes.COMMUNICATIONS_DELETE,
  PermissionCodes.COMMUNICATIONS_ATTACHMENTS,
];

const SPRINT19_TASK_LIFECYCLE: PermissionCode[] = [
  PermissionCodes.TASKS_ACCEPT,
  PermissionCodes.TASKS_START,
  PermissionCodes.TASKS_WAIT,
  PermissionCodes.TASKS_COMPLETE,
  PermissionCodes.TASKS_REJECT,
  PermissionCodes.TASKS_EVIDENCE,
  PermissionCodes.TASKS_TIMELINE,
];

const SPRINT19_TASK_MANAGE_EXTRA: PermissionCode[] = [
  PermissionCodes.TASKS_CANCEL,
  PermissionCodes.TASKS_ESCALATE,
];

/** Sprint 15 field operations — supervisory map / patrol / alert set. */
const FIELD_OPS_SUPERVISOR: PermissionCode[] = [
  PermissionCodes.FIELD_MAP_VIEW,
  PermissionCodes.SECURITY_ZONES_VIEW,
  PermissionCodes.CHECKPOINTS_VIEW,
  PermissionCodes.PATROL_ROUTES_VIEW,
  PermissionCodes.PATROL_SESSIONS_VIEW,
  PermissionCodes.PATROL_SESSIONS_CREATE,
  PermissionCodes.PATROL_SESSIONS_ASSIGN,
  PermissionCodes.PATROL_SESSIONS_START,
  PermissionCodes.PATROL_SESSIONS_COMPLETE,
  PermissionCodes.PATROL_SESSIONS_CANCEL,
  PermissionCodes.PERSONNEL_LOCATIONS_VIEW,
  PermissionCodes.PERSONNEL_LOCATIONS_UPDATE_ANY,
  PermissionCodes.FIELD_ALERTS_VIEW,
  PermissionCodes.FIELD_ALERTS_CREATE,
  PermissionCodes.FIELD_ALERTS_ACKNOWLEDGE,
  PermissionCodes.FIELD_ALERTS_RESOLVE,
];

/** Sprint 16 CCTV operations — operator (feminine role) capabilities. */
const CCTV_OPS_OPERATOR: PermissionCode[] = [
  PermissionCodes.CCTV_OPS_DASHBOARD_VIEW,
  PermissionCodes.PERMITS_VIEW,
  PermissionCodes.PERMITS_CREATE,
  PermissionCodes.PERMITS_UPDATE,
  PermissionCodes.PERMITS_ACTIVATE,
  PermissionCodes.PERMITS_CANCEL,
  PermissionCodes.PERMITS_SHARE,
  PermissionCodes.PERMITS_DOWNLOAD_ATTACHMENT,
  PermissionCodes.SECURITY_REFERRALS_VIEW,
  PermissionCodes.SECURITY_REFERRALS_CREATE,
  PermissionCodes.SECURITY_REFERRALS_UPDATE,
  PermissionCodes.SECURITY_REFERRALS_SEND,
  PermissionCodes.SECURITY_REFERRALS_CANCEL,
  PermissionCodes.SECURITY_REFERRALS_ESCALATE,
  PermissionCodes.SECURITY_REFERRALS_ADD_NOTE,
  PermissionCodes.SECURITY_REFERRALS_UPLOAD_ATTACHMENT,
  PermissionCodes.SECURITY_REFERRALS_DOWNLOAD_ATTACHMENT,
];

/** Sprint 16 — guard field response to referrals + shared permits. */
const CCTV_OPS_GUARD: PermissionCode[] = [
  PermissionCodes.PERMITS_VIEW,
  PermissionCodes.PERMITS_ACKNOWLEDGE,
  PermissionCodes.PERMITS_DOWNLOAD_ATTACHMENT,
  PermissionCodes.SECURITY_REFERRALS_VIEW,
  PermissionCodes.SECURITY_REFERRALS_RECEIVE,
  PermissionCodes.SECURITY_REFERRALS_START,
  PermissionCodes.SECURITY_REFERRALS_ARRIVE,
  PermissionCodes.SECURITY_REFERRALS_RESOLVE,
  PermissionCodes.SECURITY_REFERRALS_REJECT,
  PermissionCodes.SECURITY_REFERRALS_ADD_NOTE,
  PermissionCodes.SECURITY_REFERRALS_UPLOAD_ATTACHMENT,
  PermissionCodes.SECURITY_REFERRALS_DOWNLOAD_ATTACHMENT,
];

/** Sprint 16 — supervisor/ops referral management. */
const CCTV_OPS_SUPERVISOR: PermissionCode[] = [
  PermissionCodes.CCTV_OPS_DASHBOARD_VIEW,
  PermissionCodes.PERMITS_VIEW,
  PermissionCodes.PERMITS_SHARE,
  PermissionCodes.PERMITS_ACKNOWLEDGE,
  PermissionCodes.PERMITS_CANCEL,
  PermissionCodes.PERMITS_REJECT,
  PermissionCodes.PERMITS_DOWNLOAD_ATTACHMENT,
  PermissionCodes.SECURITY_REFERRALS_VIEW,
  PermissionCodes.SECURITY_REFERRALS_CREATE,
  PermissionCodes.SECURITY_REFERRALS_UPDATE,
  PermissionCodes.SECURITY_REFERRALS_SEND,
  PermissionCodes.SECURITY_REFERRALS_ASSIGN,
  PermissionCodes.SECURITY_REFERRALS_RECEIVE,
  PermissionCodes.SECURITY_REFERRALS_START,
  PermissionCodes.SECURITY_REFERRALS_ARRIVE,
  PermissionCodes.SECURITY_REFERRALS_RESOLVE,
  PermissionCodes.SECURITY_REFERRALS_REJECT,
  PermissionCodes.SECURITY_REFERRALS_CANCEL,
  PermissionCodes.SECURITY_REFERRALS_ESCALATE,
  PermissionCodes.SECURITY_REFERRALS_CLOSE,
  PermissionCodes.SECURITY_REFERRALS_ADD_NOTE,
  PermissionCodes.SECURITY_REFERRALS_UPLOAD_ATTACHMENT,
  PermissionCodes.SECURITY_REFERRALS_DOWNLOAD_ATTACHMENT,
];

/** Sprint 17 — Guard field incident lifecycle (no close HIGH/CRITICAL — enforced in service). */
const INCIDENT_OPS_GUARD: PermissionCode[] = [
  PermissionCodes.INCIDENTS_VIEW_ASSIGNED,
  PermissionCodes.INCIDENTS_ACKNOWLEDGE,
  PermissionCodes.INCIDENTS_RESPOND,
  PermissionCodes.INCIDENTS_ARRIVE,
  PermissionCodes.INCIDENTS_CONTAIN,
  PermissionCodes.INCIDENTS_RESOLVE,
  PermissionCodes.INCIDENTS_NOTES,
  PermissionCodes.INCIDENTS_ATTACHMENTS,
  PermissionCodes.INCIDENTS_REQUEST_SUPPORT,
];

/** Sprint 17 — Supervisor ops room + assign/close/escalate. */
const INCIDENT_OPS_SUPERVISOR: PermissionCode[] = [
  PermissionCodes.OPERATIONS_ROOM_VIEW,
  PermissionCodes.INCIDENTS_VIEW_ALL,
  PermissionCodes.INCIDENTS_ACKNOWLEDGE,
  PermissionCodes.INCIDENTS_ASSESS,
  PermissionCodes.INCIDENTS_ASSIGN,
  PermissionCodes.INCIDENTS_REASSIGN,
  PermissionCodes.INCIDENTS_RESPOND,
  PermissionCodes.INCIDENTS_ARRIVE,
  PermissionCodes.INCIDENTS_CONTAIN,
  PermissionCodes.INCIDENTS_RESOLVE,
  PermissionCodes.INCIDENTS_REOPEN,
  PermissionCodes.INCIDENTS_CANCEL,
  PermissionCodes.INCIDENTS_FALSE_ALARM,
  PermissionCodes.INCIDENTS_ESCALATE,
  PermissionCodes.INCIDENTS_REQUEST_SUPPORT,
  PermissionCodes.INCIDENTS_NOTES,
  PermissionCodes.INCIDENTS_CONTACTS,
  PermissionCodes.INCIDENTS_TASKS,
  PermissionCodes.INCIDENTS_FOLLOW_UPS,
  PermissionCodes.INCIDENTS_ATTACHMENTS,
  PermissionCodes.INCIDENTS_CONVERT_ALERT,
  PermissionCodes.INCIDENTS_CONVERT_VIOLATION,
  PermissionCodes.EMERGENCY_PROCEDURES_VIEW,
];

/** Sprint 17 — CCTV: create/view related, convert referral, escalate request, no close. */
const INCIDENT_OPS_CCTV: PermissionCode[] = [
  PermissionCodes.INCIDENTS_VIEW_ASSIGNED,
  PermissionCodes.INCIDENTS_NOTES,
  PermissionCodes.INCIDENTS_ATTACHMENTS,
  PermissionCodes.INCIDENTS_CONVERT_REFERRAL,
  PermissionCodes.INCIDENTS_ESCALATE,
  PermissionCodes.INCIDENTS_REQUEST_SUPPORT,
];

/** Sprint 17 — Ops manager: full ops room + manage procedures + close. */
const INCIDENT_OPS_MANAGER: PermissionCode[] = [
  PermissionCodes.OPERATIONS_ROOM_VIEW,
  PermissionCodes.OPERATIONS_ROOM_MANAGE,
  PermissionCodes.INCIDENTS_VIEW_ALL,
  PermissionCodes.INCIDENTS_ACKNOWLEDGE,
  PermissionCodes.INCIDENTS_ASSESS,
  PermissionCodes.INCIDENTS_ASSIGN,
  PermissionCodes.INCIDENTS_REASSIGN,
  PermissionCodes.INCIDENTS_RESPOND,
  PermissionCodes.INCIDENTS_ARRIVE,
  PermissionCodes.INCIDENTS_CONTAIN,
  PermissionCodes.INCIDENTS_RESOLVE,
  PermissionCodes.INCIDENTS_REOPEN,
  PermissionCodes.INCIDENTS_CANCEL,
  PermissionCodes.INCIDENTS_FALSE_ALARM,
  PermissionCodes.INCIDENTS_ESCALATE,
  PermissionCodes.INCIDENTS_REQUEST_SUPPORT,
  PermissionCodes.INCIDENTS_NOTES,
  PermissionCodes.INCIDENTS_NOTES_CONFIDENTIAL,
  PermissionCodes.INCIDENTS_CONTACTS,
  PermissionCodes.INCIDENTS_TASKS,
  PermissionCodes.INCIDENTS_FOLLOW_UPS,
  PermissionCodes.INCIDENTS_ATTACHMENTS,
  PermissionCodes.INCIDENTS_CONVERT_REFERRAL,
  PermissionCodes.INCIDENTS_CONVERT_ALERT,
  PermissionCodes.INCIDENTS_CONVERT_VIOLATION,
  PermissionCodes.EMERGENCY_PROCEDURES_VIEW,
  PermissionCodes.EMERGENCY_PROCEDURES_MANAGE,
];

/** Sprint 18 — Reports / KPI / Audit Logs */
const REPORTS_GUARD: PermissionCode[] = [
  PermissionCodes.REPORTS_VIEW,
  PermissionCodes.REPORTS_LIST,
  PermissionCodes.REPORTS_KPI_VIEW,
  PermissionCodes.KPI_SHIFTS,
  PermissionCodes.KPI_PERSONNEL,
];

const REPORTS_SUPERVISOR: PermissionCode[] = [
  ...REPORTS_GUARD,
  PermissionCodes.REPORTS_DASHBOARD_VIEW,
  PermissionCodes.REPORTS_GENERATE_SHIFT,
  PermissionCodes.REPORTS_GENERATE_HANDOVER,
  PermissionCodes.REPORTS_SUBMIT,
  PermissionCodes.REPORTS_EXPORT_PDF,
  PermissionCodes.REPORTS_EXPORT_CSV,
  PermissionCodes.REPORTS_CREATE_VERSION,
  PermissionCodes.KPI_VIEW,
  PermissionCodes.KPI_INCIDENTS,
  PermissionCodes.KPI_RESPONSE_TIMES,
  PermissionCodes.KPI_PATROLS,
  PermissionCodes.KPI_VIOLATIONS,
  PermissionCodes.KPI_GROUPS,
  PermissionCodes.KPI_SHIFTS,
];

const REPORTS_CCTV: PermissionCode[] = [
  PermissionCodes.REPORTS_VIEW,
  PermissionCodes.REPORTS_LIST,
  PermissionCodes.REPORTS_KPI_VIEW,
  PermissionCodes.KPI_CCTV_REFERRALS,
  PermissionCodes.KPI_PERMITS,
];

const REPORTS_OPS_MANAGER: PermissionCode[] = [
  ...REPORTS_SUPERVISOR,
  PermissionCodes.REPORTS_READ,
  PermissionCodes.REPORTS_GENERATE,
  PermissionCodes.REPORTS_GENERATE_DAILY,
  PermissionCodes.REPORTS_GENERATE_CUSTOM,
  PermissionCodes.REPORTS_SCHEDULES_VIEW,
  PermissionCodes.REPORTS_SCHEDULES_MANAGE,
  PermissionCodes.REPORTS_ACCESS_LOG_VIEW,
  PermissionCodes.REPORTS_RETURN,
  PermissionCodes.KPI_VISITORS,
  PermissionCodes.AUDIT_LOGS_VIEW,
  PermissionCodes.AUDIT_LOGS_STATISTICS,
  PermissionCodes.AUDIT_LOGS_EXPORT,
];

const REPORTS_PROJECT_MANAGER: PermissionCode[] = [
  PermissionCodes.REPORTS_READ,
  PermissionCodes.REPORTS_DASHBOARD_VIEW,
  PermissionCodes.REPORTS_LIST,
  PermissionCodes.REPORTS_VIEW,
  PermissionCodes.REPORTS_EXPORT_PDF,
  PermissionCodes.REPORTS_EXPORT_CSV,
  PermissionCodes.REPORTS_KPI_VIEW,
  PermissionCodes.KPI_VIEW,
  PermissionCodes.AUDIT_LOGS_VIEW,
  PermissionCodes.AUDIT_LOGS_STATISTICS,
];

/** Sprint 20 — mobile app core (bootstrap / sync / offline). */
const SPRINT20_MOBILE_CORE: PermissionCode[] = [
  PermissionCodes.MOBILE_APP_ACCESS,
  PermissionCodes.MOBILE_BOOTSTRAP,
  PermissionCodes.MOBILE_SYNC,
  PermissionCodes.MOBILE_OFFLINE_OPERATIONS,
  PermissionCodes.MOBILE_DEVICES_MANAGE_SELF,
  PermissionCodes.MOBILE_SYNC_ISSUES_VIEW,
];

/** Sprint 20 — guard field mobile capabilities. */
const SPRINT20_MOBILE_GUARD: PermissionCode[] = [
  ...SPRINT20_MOBILE_CORE,
  PermissionCodes.MOBILE_DASHBOARD_GUARD,
  PermissionCodes.MOBILE_INCIDENTS_VIEW,
  PermissionCodes.MOBILE_INCIDENTS_RESPOND,
  PermissionCodes.MOBILE_INCIDENTS_CREATE,
  PermissionCodes.MOBILE_TASKS_VIEW,
  PermissionCodes.MOBILE_TASKS_UPDATE,
  PermissionCodes.MOBILE_PATROLS_VIEW,
  PermissionCodes.MOBILE_PATROLS_EXECUTE,
  PermissionCodes.MOBILE_CHECKPOINTS_SCAN,
  PermissionCodes.MOBILE_REFERRALS_VIEW,
  PermissionCodes.MOBILE_REFERRALS_RESPOND,
  PermissionCodes.MOBILE_PERMITS_VIEW,
  PermissionCodes.MOBILE_PERMITS_ACKNOWLEDGE,
  PermissionCodes.MOBILE_VIOLATIONS_VIEW,
  PermissionCodes.MOBILE_VIOLATIONS_CREATE,
  PermissionCodes.MOBILE_HANDOVER_VIEW,
  PermissionCodes.MOBILE_SOS_CREATE,
  PermissionCodes.MOBILE_COMMUNICATIONS_VIEW,
  PermissionCodes.MOBILE_COMMUNICATIONS_SEND,
];

/** Sprint 20 — supervisor mobile (handover submit/receive + broader respond). */
const SPRINT20_MOBILE_SUPERVISOR: PermissionCode[] = [
  ...SPRINT20_MOBILE_GUARD,
  PermissionCodes.MOBILE_DASHBOARD_SUPERVISOR,
  PermissionCodes.MOBILE_HANDOVER_SUBMIT,
  PermissionCodes.MOBILE_HANDOVER_RECEIVE,
  PermissionCodes.MOBILE_REFERRALS_CREATE,
];

/** Sprint 20 — CCTV operator mobile (no field patrol execute). */
const SPRINT20_MOBILE_CCTV: PermissionCode[] = [
  ...SPRINT20_MOBILE_CORE,
  PermissionCodes.MOBILE_DASHBOARD_CCTV,
  PermissionCodes.MOBILE_INCIDENTS_VIEW,
  PermissionCodes.MOBILE_INCIDENTS_CREATE,
  PermissionCodes.MOBILE_TASKS_VIEW,
  PermissionCodes.MOBILE_REFERRALS_VIEW,
  PermissionCodes.MOBILE_REFERRALS_CREATE,
  PermissionCodes.MOBILE_PERMITS_VIEW,
  PermissionCodes.MOBILE_PERMITS_CREATE,
  PermissionCodes.MOBILE_VIOLATIONS_VIEW,
  PermissionCodes.MOBILE_VIOLATIONS_CREATE,
  PermissionCodes.MOBILE_HANDOVER_VIEW,
  PermissionCodes.MOBILE_COMMUNICATIONS_VIEW,
  PermissionCodes.MOBILE_COMMUNICATIONS_SEND,
];

/** Sprint 20 — operations manager mobile. */
const SPRINT20_MOBILE_OPS: PermissionCode[] = [
  ...SPRINT20_MOBILE_SUPERVISOR,
  PermissionCodes.MOBILE_DASHBOARD_OPERATIONS,
  PermissionCodes.MOBILE_DEVICES_MANAGE_ALL,
];

/** Sprint 20 — director / project manager: dashboards + devices all + sync issues (not flood create). */
const SPRINT20_MOBILE_DIRECTOR: PermissionCode[] = [
  PermissionCodes.MOBILE_APP_ACCESS,
  PermissionCodes.MOBILE_BOOTSTRAP,
  PermissionCodes.MOBILE_SYNC,
  PermissionCodes.MOBILE_DASHBOARD_GUARD,
  PermissionCodes.MOBILE_DASHBOARD_SUPERVISOR,
  PermissionCodes.MOBILE_DASHBOARD_CCTV,
  PermissionCodes.MOBILE_DASHBOARD_OPERATIONS,
  PermissionCodes.MOBILE_INCIDENTS_VIEW,
  PermissionCodes.MOBILE_TASKS_VIEW,
  PermissionCodes.MOBILE_PATROLS_VIEW,
  PermissionCodes.MOBILE_REFERRALS_VIEW,
  PermissionCodes.MOBILE_PERMITS_VIEW,
  PermissionCodes.MOBILE_VIOLATIONS_VIEW,
  PermissionCodes.MOBILE_HANDOVER_VIEW,
  PermissionCodes.MOBILE_COMMUNICATIONS_VIEW,
  PermissionCodes.MOBILE_SYNC_ISSUES_VIEW,
  PermissionCodes.MOBILE_DEVICES_MANAGE_SELF,
  PermissionCodes.MOBILE_DEVICES_MANAGE_ALL,
];

/** Default permission grants per role (static RolePermission seed). */
export const ROLE_PERMISSION_GRANTS: Record<string, PermissionCode[]> = {
  SECURITY_GUARD: [
    ...SPRINT10_BASE,
    ...SPRINT19_NOTIFICATIONS_BASE,
    ...SPRINT19_COMMS_BASE,
    ...SPRINT19_TASK_LIFECYCLE,
    PermissionCodes.TASKS_UPDATE,
    PermissionCodes.USERS_READ,
    PermissionCodes.INCIDENTS_READ,
    PermissionCodes.INCIDENTS_CREATE,
    PermissionCodes.INCIDENTS_COMMENT,
    ...INCIDENT_OPS_GUARD,
    PermissionCodes.PATROLS_READ,
    PermissionCodes.PATROLS_CREATE,
    PermissionCodes.PATROLS_UPDATE,
    PermissionCodes.VIOLATIONS_READ,
    PermissionCodes.VIOLATIONS_CREATE,
    PermissionCodes.VISITORS_READ,
    PermissionCodes.HOSTS_READ,
    PermissionCodes.MEETING_ROOMS_READ,
    PermissionCodes.FLOORS_READ,
    PermissionCodes.SHIFTS_READ,
    PermissionCodes.FIELD_MAP_VIEW,
    PermissionCodes.CHECKPOINTS_VIEW,
    PermissionCodes.PATROL_SESSIONS_VIEW,
    PermissionCodes.PATROL_SESSIONS_START,
    PermissionCodes.PATROL_SESSIONS_COMPLETE,
    PermissionCodes.PERSONNEL_LOCATIONS_UPDATE_SELF,
    PermissionCodes.FIELD_ALERTS_VIEW,
    PermissionCodes.FIELD_ALERTS_CREATE,
    ...CCTV_OPS_GUARD,
    ...REPORTS_GUARD,
    ...SPRINT20_MOBILE_GUARD,
  ],
  SECURITY_SUPERVISOR: [
    ...SPRINT10_BASE,
    ...SPRINT10_TASK_MANAGE,
    ...SPRINT19_NOTIFICATIONS_BASE,
    ...SPRINT19_COMMS_BASE,
    ...SPRINT19_TASK_LIFECYCLE,
    ...SPRINT19_TASK_MANAGE_EXTRA,
    PermissionCodes.NOTIFICATIONS_RULES_READ,
    PermissionCodes.USERS_READ,
    PermissionCodes.USERS_READ_PHONE,
    PermissionCodes.INCIDENTS_READ,
    PermissionCodes.INCIDENTS_CREATE,
    PermissionCodes.INCIDENTS_UPDATE,
    PermissionCodes.INCIDENTS_HANDLE,
    PermissionCodes.INCIDENTS_CLOSE,
    PermissionCodes.INCIDENTS_COMMENT,
    ...INCIDENT_OPS_SUPERVISOR,
    PermissionCodes.PATROLS_READ,
    PermissionCodes.PATROLS_CREATE,
    PermissionCodes.PATROLS_UPDATE,
    PermissionCodes.VIOLATIONS_READ,
    PermissionCodes.VIOLATIONS_UPDATE,
    PermissionCodes.VIOLATIONS_ASSIGN,
    PermissionCodes.VIOLATIONS_CLOSE,
    PermissionCodes.VIOLATIONS_STATS,
    PermissionCodes.COMPLAINTS_READ,
    PermissionCodes.VISITORS_READ,
    PermissionCodes.VISITORS_CREATE,
    PermissionCodes.VISITORS_UPDATE,
    PermissionCodes.VISITORS_ARRIVE,
    PermissionCodes.VISITORS_STATS,
    PermissionCodes.HOSTS_READ,
    PermissionCodes.HOSTS_CREATE,
    PermissionCodes.HOSTS_UPDATE,
    PermissionCodes.MEETING_ROOMS_READ,
    PermissionCodes.MEETING_ROOMS_MANAGE,
    PermissionCodes.FLOORS_READ,
    PermissionCodes.FLOORS_UPDATE,
    PermissionCodes.CAMERA_REQUESTS_READ,
    PermissionCodes.CAMERA_REQUESTS_CREATE,
    PermissionCodes.CCTV_DASHBOARD_READ,
    PermissionCodes.SHIFTS_READ,
    PermissionCodes.SHIFTS_UPDATE,
    PermissionCodes.SHIFTS_HANDOVER,
    PermissionCodes.SHIFTS_STATS,
    ...FIELD_OPS_SUPERVISOR,
    ...CCTV_OPS_SUPERVISOR,
    ...REPORTS_SUPERVISOR,
    ...SPRINT20_MOBILE_SUPERVISOR,
  ],
  CCTV_OPERATOR: [
    ...SPRINT10_BASE,
    ...SPRINT19_NOTIFICATIONS_BASE,
    ...SPRINT19_COMMS_BASE,
    PermissionCodes.USERS_READ,
    PermissionCodes.VIOLATIONS_READ,
    PermissionCodes.VIOLATIONS_CREATE,
    PermissionCodes.VIOLATIONS_UPDATE,
    PermissionCodes.VIOLATIONS_ASSIGN,
    PermissionCodes.INCIDENTS_READ,
    PermissionCodes.INCIDENTS_CREATE,
    PermissionCodes.INCIDENTS_COMMENT,
    ...INCIDENT_OPS_CCTV,
    PermissionCodes.VISITORS_READ,
    PermissionCodes.CAMERA_REQUESTS_READ,
    PermissionCodes.CAMERA_REQUESTS_HANDLE,
    PermissionCodes.VEHICLE_PERMITS_READ,
    PermissionCodes.CCTV_DASHBOARD_READ,
    PermissionCodes.SHIFTS_READ,
    PermissionCodes.FIELD_MAP_VIEW,
    PermissionCodes.SECURITY_ZONES_VIEW,
    PermissionCodes.CHECKPOINTS_VIEW,
    PermissionCodes.FIELD_ALERTS_VIEW,
    PermissionCodes.FIELD_ALERTS_CREATE,
    ...CCTV_OPS_OPERATOR,
    ...REPORTS_CCTV,
    ...SPRINT20_MOBILE_CCTV,
  ],
  OPERATIONS_MANAGER: [
    ...SPRINT10_BASE,
    ...SPRINT10_TASK_MANAGE,
    ...SPRINT19_NOTIFICATIONS_BASE,
    ...SPRINT19_COMMS_BASE,
    ...SPRINT19_TASK_LIFECYCLE,
    ...SPRINT19_TASK_MANAGE_EXTRA,
    PermissionCodes.NOTIFICATIONS_RULES_READ,
    PermissionCodes.NOTIFICATIONS_RULES_MANAGE,
    PermissionCodes.COMMUNICATIONS_MANAGE,
    PermissionCodes.USERS_READ,
    PermissionCodes.USERS_CREATE,
    PermissionCodes.USERS_UPDATE,
    PermissionCodes.USERS_READ_PHONE,
    PermissionCodes.ROLES_READ,
    PermissionCodes.INCIDENTS_READ,
    PermissionCodes.INCIDENTS_CREATE,
    PermissionCodes.INCIDENTS_UPDATE,
    PermissionCodes.INCIDENTS_HANDLE,
    PermissionCodes.INCIDENTS_CLOSE,
    PermissionCodes.INCIDENTS_COMMENT,
    ...INCIDENT_OPS_MANAGER,
    PermissionCodes.PATROLS_READ,
    PermissionCodes.PATROLS_CREATE,
    PermissionCodes.PATROLS_UPDATE,
    PermissionCodes.VIOLATIONS_READ,
    PermissionCodes.VIOLATIONS_CREATE,
    PermissionCodes.VIOLATIONS_UPDATE,
    PermissionCodes.VIOLATIONS_ASSIGN,
    PermissionCodes.VIOLATIONS_CLOSE,
    PermissionCodes.VIOLATIONS_STATS,
    PermissionCodes.COMPLAINTS_READ,
    PermissionCodes.COMPLAINTS_CREATE,
    PermissionCodes.COMPLAINTS_UPDATE,
    PermissionCodes.COMPLAINTS_APPROVE,
    PermissionCodes.COMPLAINTS_REJECT,
    PermissionCodes.REPORTS_READ,
    PermissionCodes.SETTINGS_READ,
    PermissionCodes.SETTINGS_UPDATE,
    PermissionCodes.AUDIT_READ,
    PermissionCodes.VISITORS_READ,
    PermissionCodes.VISITORS_CREATE,
    PermissionCodes.VISITORS_UPDATE,
    PermissionCodes.VISITORS_ARRIVE,
    PermissionCodes.VISITORS_STATS,
    PermissionCodes.HOSTS_READ,
    PermissionCodes.HOSTS_CREATE,
    PermissionCodes.HOSTS_UPDATE,
    PermissionCodes.HOSTS_DELETE,
    PermissionCodes.MEETING_ROOMS_READ,
    PermissionCodes.MEETING_ROOMS_MANAGE,
    PermissionCodes.FLOORS_READ,
    PermissionCodes.FLOORS_UPDATE,
    PermissionCodes.VISIT_EMAILS_READ,
    PermissionCodes.VISIT_EMAILS_INGEST,
    PermissionCodes.CAMERA_REQUESTS_READ,
    PermissionCodes.CAMERA_REQUESTS_CREATE,
    PermissionCodes.CAMERA_REQUESTS_HANDLE,
    PermissionCodes.VEHICLE_PERMITS_READ,
    PermissionCodes.CCTV_DASHBOARD_READ,
    PermissionCodes.SHIFTS_READ,
    PermissionCodes.SHIFTS_UPDATE,
    PermissionCodes.SHIFTS_MANAGE,
    PermissionCodes.SHIFTS_HANDOVER,
    PermissionCodes.SHIFTS_STATS,
    ...FIELD_OPS_SUPERVISOR,
    PermissionCodes.FIELD_MAP_MANAGE,
    PermissionCodes.SECURITY_ZONES_CREATE,
    PermissionCodes.SECURITY_ZONES_UPDATE,
    PermissionCodes.SECURITY_ZONES_DELETE,
    PermissionCodes.CHECKPOINTS_CREATE,
    PermissionCodes.CHECKPOINTS_UPDATE,
    PermissionCodes.CHECKPOINTS_DELETE,
    PermissionCodes.PATROL_ROUTES_MANAGE,
    ...CCTV_OPS_SUPERVISOR,
    PermissionCodes.PERMITS_VIEW_SENSITIVE,
    ...REPORTS_OPS_MANAGER,
    ...SPRINT20_MOBILE_OPS,
  ],
  PROJECT_MANAGER: [
    ...SPRINT10_BASE,
    ...SPRINT19_NOTIFICATIONS_BASE,
    PermissionCodes.COMMUNICATIONS_READ,
    PermissionCodes.USERS_READ,
    PermissionCodes.ROLES_READ,
    PermissionCodes.COMPLAINTS_READ,
    PermissionCodes.INCIDENTS_READ,
    PermissionCodes.PATROLS_READ,
    PermissionCodes.VIOLATIONS_READ,
    PermissionCodes.VIOLATIONS_STATS,
    PermissionCodes.VISITORS_READ,
    PermissionCodes.VISITORS_STATS,
    PermissionCodes.HOSTS_READ,
    PermissionCodes.MEETING_ROOMS_READ,
    PermissionCodes.FLOORS_READ,
    PermissionCodes.AUDIT_READ,
    PermissionCodes.REPORTS_READ,
    PermissionCodes.CCTV_DASHBOARD_READ,
    PermissionCodes.SHIFTS_READ,
    PermissionCodes.SHIFTS_STATS,
    PermissionCodes.SHIFTS_HANDOVER,
    PermissionCodes.FIELD_MAP_VIEW,
    PermissionCodes.FIELD_MAP_MANAGE,
    PermissionCodes.SECURITY_ZONES_VIEW,
    PermissionCodes.CHECKPOINTS_VIEW,
    PermissionCodes.PATROL_ROUTES_VIEW,
    PermissionCodes.PATROL_ROUTES_MANAGE,
    PermissionCodes.PATROL_SESSIONS_VIEW,
    PermissionCodes.PERSONNEL_LOCATIONS_VIEW,
    PermissionCodes.FIELD_ALERTS_VIEW,
    PermissionCodes.CCTV_OPS_DASHBOARD_VIEW,
    PermissionCodes.PERMITS_VIEW,
    PermissionCodes.SECURITY_REFERRALS_VIEW,
    PermissionCodes.OPERATIONS_ROOM_VIEW,
    PermissionCodes.EMERGENCY_PROCEDURES_VIEW,
    ...REPORTS_PROJECT_MANAGER,
    ...SPRINT20_MOBILE_DIRECTOR,
  ],
  SECURITY_DIRECTOR: PERMISSION_CATALOG.map((p) => p.code),
};
